---
- include: init.yml
- name: Create directory
  file: path={{ directory }} state=directory
- name: Download binary
  get_url: url=https://download.elastic.co/logstash-forwarder/binaries/logstash-forwarder_linux_amd64 dest={{ directory }}/logstash-forwarder mode=755
  notify: Restart logstash-forwarder
- name: Create configuration
  template: src=logstash-forwarder.json.j2 dest={{ directory }}/logstash-forwarder.json
  notify: Restart logstash-forwarder
- name: Copy Logstash server certificate
  copy: src={{ certificate }} dest={{ directory }}/logstash.crt
  notify: Restart logstash-forwarder
- name: Register service
  template: src=logstash-forwarder.upstart.conf.j2 dest=/etc/init/logstash-forwarder.conf
  notify: Restart logstash-forwarder
- name: Start service
  service: name=logstash-forwarder state=started enabled=yes
